name: Update to latest version

on:
  workflow_dispatch:
  schedule:
  - cron: '00 12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: longhorn/longhorn-manager
        ref: v1.2.2
        path: upstream
    - name: Update image version
      run: scripts/update_image.sh
    - uses: imranismail/setup-kustomize@v1
    - name: Update kustomization files
      run: scripts/update_kustomization.sh
    - name: Cleanup
      run: rm -rf ./upstream
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
        title: "[bot] Automated update"
        signoff: false
        committer: Github <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: |
          This is an automated update to longhorn manifests from CI.

          Configuration of the workflow is located in `.github/workflows/update.yaml`
        labels: bot/update
